### ISSUE TITLE
對話文本沒有出現雙字幕

### ISSUE THREAD

**Issue by JerryMushrooom** [JungleDruid/BG3LocalizationMerger#2]
您好
照著教學完成安裝之後
唯獨書籍及對話時的字幕是只有單字幕的
但是用無條件合併的話 所有的字幕都有雙字幕
可是這樣有些文本就會被蓋住看不到 也不美觀
想請問該如何解決呢?

**Comment by JungleDruid** [comment]
請問你的合併記錄裡，對話和書的數量有多少個呢？

如果很少或甚至是0個，有可能是解壓縮和解包的步驟有出問題

![image](https://github.com/JungleDruid/BG3LocalizationMerger/assets/3953982/d908b102-c83c-41e2-ae19-263f2777e4b2)

**Comment by JerryMushrooom** [comment]
這部分我沒有細看不太清楚...
我現在再解壓一次確認一下

**Comment by JerryMushrooom** [comment]
真的耶  對話跟書籍的數量是0

解壓縮出來的檔案有這幾個
容量蠻大的有20幾G
應該有包含到對話的文本了吧...?

![image](https://github.com/JungleDruid/BG3LocalizationMerger/assets/159997247/23885eb4-fd0a-47e4-a1cb-2353b38349d2)

**Comment by JungleDruid** [comment]
資料夾看起來沒問題，試試看重新解壓

![image](https://github.com/JungleDruid/BG3LocalizationMerger/assets/3953982/611ac3e0-55d1-4e68-92e5-e69f495f0571)

**Comment by JerryMushrooom** [comment]
成功了! 太感謝了!
期待用雙字幕玩第二輪
謝謝幫忙!
